data = [
    {
        "id": 8812,
        "uri": "http://rdf-vocabulary.ddialliance.org/cv/TypeOfAddress/1.1/[CODE]",
        "notation": "Mailing",
        "title": "Mailing address",
        "definition": 'Includes both "street"',
        "previousConcept": 3535,
        "position": 0,
        "deprecated": False,
    },
    {
        "id": 8817,
        "uri": "http://rdf-vocabulary.ddialliance.org/cv/TypeOfAddress/1.1/[CODE]",
        "notation": "Mailing.Residential",
        "title": "Mailing address: Residential",
        "definition": "Address for directing physical/conventional mail to a person's residence,",
        "previousConcept": 3536,
        "parent": "Mailing",
        "position": 1,
        "deprecated": False,
    },
    {
        "id": 8814,
        "uri": "http://rdf-vocabulary.ddialliance.org/cv/TypeOfAddress/1.1/[CODE]",
        "notation": "Mailing.Nonresidential",
        "title": "Mailing address: Nonresidential",
        "definition": "Address for directing physical/conventional mail to a business,",
        "previousConcept": 3537,
        "parent": "Mailing",
        "position": 2,
        "deprecated": False,
    },
    {
        "id": 14169,
        "uri": "https://vocabularies.cessda.eu/vocabulary/TopicClassification_[CODE]?v=4.2",
        "notation": "Health.ReproductiveHealth",
        "title": "Reproductive health",
        "definition": "Reproductive process, function or system at any stage of life. Includes data on pregnancy, birth, ",
        "previousConcept": 8897,
        "parent": "Health",
        "position": 25,
        "deprecated": False,
    },
    {
        "id": 14131,
        "uri": "https://vocabularies.cessda.eu/vocabulary/TopicClassification_[CODE]?v=4.2",
        "notation": "Health.SignsAndSymptomsPathologicalConditions",
        "title": "Signs and symptoms; pathological conditions",
        "definition": "Data on abnormal anatomical or physiological conditions",
        "previousConcept": 8961,
        "parent": "Health",
        "position": 26,
        "deprecated": False,
    },
]

res_data = [
    "https://vocabularies.cessda.eu/vocabulary/TypeOfAddress_Mailing?v=1.1&id=8812",
    "https://vocabularies.cessda.eu/vocabulary/TypeOfAddress_Residential?v=1.1&id=8817",
    "https://vocabularies.cessda.eu/vocabulary/TypeOfAddress_Nonresidential?v=1.1&id=8814",
    "https://vocabularies.cessda.eu/vocabulary/TopicClassification_ReproductiveHealth?v=4.2&id=14169",
    "https://vocabularies.cessda.eu/vocabulary/TopicClassification_SignsAndSymptomsPathologicalConditions?v=4.2&id=14131",
]
